# Generated by Django 5.0.6 on 2024-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplebackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
